In [1]:
import sqlite3
import json
import codecs

conn = sqlite3.connect('geodata.sqlite')
cur = conn.cursor()

cur.execute('SELECT * FROM Locations')
fhand = codecs.open('where.js', 'w', "utf-8")
fhand.write("myData = [\n")
count = 0
for row in cur :
    data = str(row[1].decode())
    try: js = json.loads(str(data))
    except: continue

    if not('status' in js and js['status'] == 'OK') : continue

    lat = js["results"][0]["geometry"]["location"]["lat"]
    lng = js["results"][0]["geometry"]["location"]["lng"]
    if lat == 0 or lng == 0 : continue
    where = js['results'][0]['formatted_address']
    where = where.replace("'", "")
    try :
        print(where, lat, lng)

        count = count + 1
        if count > 1 : fhand.write(",\n")
        output = "["+str(lat)+","+str(lng)+", '"+where+"']"
        fhand.write(output)
    except:
        continue

fhand.write("\n];\n")
cur.close()
fhand.close()
print(count, "records written to where.js")
print("Open where.html to view the data in a browser")

aleja Adama Mickiewicza 30, 30-059 Kraków, Poland 50.06688579999999 19.9136192
Krakowskie Przedmieście 5, 00-068 Warszawa, Poland 52.2394019 21.0150792
AUC Avenue، Road، First New Cairo, Cairo Governorate 11835, Egypt 30.018923 31.499674
411 N Central Ave, Phoenix, AZ 85004, USA 33.5074106 -112.0650182
2500 Daniells Bridge Rd #300, Athens, GA 30606, USA 33.9094132 -83.4603953
Vidya Vihar, Pilani, Rajasthan 333031, India 28.3588163 75.58802039999999
Ilishan-Remo, Nigeria 6.8939569 3.7187158
Ajagara, Varanasi, Uttar Pradesh 221005, India 25.2677203 82.99125819999999
Mysore Rd, Jnana Bharathi, Bengaluru, Karnataka 560056, India 12.9503878 77.5022224
1311 S 5th St, Waco, TX 76706, USA 31.5469132 -97.1210998
19 Xinjiekou Outer St, Bei Tai Ping Zhuang, Haidian Qu, Beijing Shi, China, 100875 39.9619537 116.3662615
praspiekt Niezaliežnasci 4, Minsk, Belarus 53.8938988 27.5460609
Studentski trg 1, Beograd, Serbia 44.8184518 20.4575913
700 College St, Beloit, WI 53511, USA 42.5030333 -89.0309048
praspiekt Niezaliežnasci 4, Minsk, Belarus 53.8938988 27.5460609
שד בן-גוריון 1, באר שבע, Israel 31.262218 34.801461
Palkalaiperur, Tiruchirappalli, Tamil Nadu 620024, India 10.6779085 78.74454879999999
Boston, MA 02215, USA 42.3504997 -71.1053991
San Luis Obispo, CA 93407, USA 35.3050053 -120.6624942
5500 University Pkwy, San Bernardino, CA 92407, USA 34.1817955 -117.3237219
25 Paddington Green, London W2 1NB, UK 51.5210038 -0.1746353
New York, NY 10027, USA 40.8075355 -73.9625727
College Rd, Cranfield, Wharley End, Bedford MK43 0AL, UK 52.0746136 -0.6282833
166 36 Prague 6, Czechia 50.1030364 14.3912841
Hanover, NH 03755, USA 43.7044406 -72.2886935
21250 Stevens Creek Blvd, Cupertino, CA 95014, USA 37.3206678 -122.0454878
Universitätsstraße 47, 58097 Hagen, Germany 51.3774422 7.493855399999999
Haharina Ave, 72, Dnipropetrovsk, Dnipropetrovska oblast, Ukraine, 49000 48.4331922 35.0427966
No: 144 35210, Alsancak, Cumhuriyet Blv, 35220 Konak/İzmir, Turkey 38.430691 27.13692
3141 Chestnut St, Philadelphia, PA 19104, USA 39.9566127 -75.18994409999999
Austin, TX 78712, USA 30.2849185 -97.7340567
Durham, NC 27708, USA 36.0014258 -78.9382286
23 Avenue Guy de Collongue, 69130 Écully, France 45.7864448 4.7641329
CentraleSupélec, 3 Rue Joliot Curie, 91190 Gif-sur-Yvette, France 48.7087594 2.1640062
50 Campus Drive, Elon, NC 27244, USA 36.1026877 -79.5023313
Spangsbjerg Kirkevej 103, 6700 Esbjerg, Denmark 55.48843069999999 8.4467103
Vía Perimetral 5, Guayaquil, Ecuador -2.1481458 -79.9644885
Münsterstraße 156, 40476 Düsseldorf, Germany 51.2468622 6.791686899999999
Urstein Süd 1, 5412 Puch bei Hallein, Austria 47.7233835 13.0871253
Av. Tiradentes, 615 - Bom Retiro, São Paulo - SP, 01124-060, Brazil -23.5295777 -46.6325629
Trg Dositeja Obradovića 6, Novi Sad 106314, Serbia 45.2461012 19.8516968
2350 NY-110, Farmingdale, NY 11735, USA 40.7529512 -73.4267093
Av. Pres. Antônio Carlos, 6627 - Pampulha, Belo Horizonte - MG, 31270-901, Brazil -19.870682 -43.9677359
777 Glades Rd, Boca Raton, FL 33431, USA 26.3749876 -80.10106329999999
40 University Dr, Rindge, NH 03461, USA 42.7789743 -72.05553929999999
Jalukbari, Guwahati, Assam 781014, India 26.1543199 91.66316789999999
4400 University Dr, Fairfax, VA 22030, USA 38.8298118 -77.3073606
600 New Jersey Ave NW, Washington, DC 20001, USA 38.8977953 -77.0129087
Atlanta, GA 30302, USA 33.753068 -84.38528190000001
Grandville, MI, USA 42.9097484 -85.7630885
Andreas Vesaliusstraat 13, 3000 Leuven, Belgium 50.8748769 4.7077753
GJ SH 41, near Visat Three Roads, Nigam Nagar, Chandkheda, Ahmedabad, Gujarat 382424, India 23.1059226 72.59372979999999
1 Đại Cồ Việt, Bách Khoa, Hai Bà Trưng, Hà Nội, Vietnam 21.0048067 105.8453406
Jerusalem 31.7945578 35.2414009
Professor CR Rao Rd, Gachibowli, Hyderabad, Telangana 500032, India 17.4448019 78.3497604
Kalyanpur, Kanpur, Uttar Pradesh 208016, India 26.5123388 80.2329
Raja 4, 12616 Tallinn, Estonia 59.3954769 24.6643815
107 S Indiana Ave, Bloomington, IN 47405, USA 39.1754487 -86.512627
Santa Croce, 191, 30135 Venezia VE, Italy 45.4377574 12.3223297
10 W 35th St, Chicago, IL 60616, USA 41.8348731 -87.6270059
60 records written to where.js
Open where.html to view the data in a browser